// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmdrhlpnwoblmrhcmzez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZHJobHBud29ibG1yaGNtemV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzQxODQsImV4cCI6MjA2MDcxMDE4NH0.Kez3UBQX_9HGlz6i4EJjpzBoFsEEhnFYqe6X8EKi5sk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);